channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy=1.26
  - pytorch=2.8
  - torchvision
  - pytorch-cuda=12.8
  - scikit-image
  - scikit-learn
  - scipy
  - pandas
  - matplotlib
  - opencv
  - numba
  - tqdm

  - pip:
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - lpips==0.1.4
      - insightface==0.7.3
      - facenet-pytorch==2.6.0
      - face-alignment==1.4.1
      - moviepy==1.0.3
      - albumentations==1.3.1
      - mtcnn==1.0.0
      - mtcnn-pytorch==1.0.2
      - onnx==1.15.0
      - onnxruntime-gpu==1.23.2
      - deepface==0.0.93
      - retina-face==0.0.17
      - kornia==0.7.4
