facenet_512:
  enable: true
  threshold: 1.04

face_recognition:
  enable: true

facepp:
  enable: false
  qps: 10
  thread_limit: 5
  compare_url: "https://api-us.faceplusplus.com/facepp/v3/compare"
  detect_url: "https://api-us.faceplusplus.com/facepp/v3/detect"
  api_key: ""
  api_secret: ""

aws:
  enable: false
  api_key: ""
  api_secret: ""
  api_region: "us-west-2"

ai_lab_tools:
  qps: 10
  face_beauty_url: "https://www.ailabapi.com/api/portrait/effects/face-beauty"
  api_key: ""

tencent_cloud:
  qps: 10
  secret_id: ""
  secret_key: ""

score:
  identity: 1
  context: 1
  trace: 1

effectiveness:
  perturb: true
  ASRo: true
  ASRp: true
  TSR: true