defaults:
  - evaluate: evaluate
  - third_party: simswap
  - _self_

log:
  file_suffix: ""
  record_level: info # one of [debug, info, warning, error, critical]

log_dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}${log.file_suffix}
image_dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}${log.file_suffix}/image
random_seed: 0

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}${log.file_suffix}
  output_subdir: config