defaults:
  - evaluate: evaluate
  - third_party: simswap
  - _self_

log:
  file_suffix: ""
  record_level: info # one of [debug, info, warning, error, critical]

log_dir: ${hydra:runtime.output_dir}${log.file_suffix}
image_dir: ${log_dir}/image
random_seed: 2025

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}${log.file_suffix}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}${log.file_suffix}
  output_subdir: config