defaults:
  - evaluate: evaluate
  - protection: phantomseal
  - third_party: simswap
  - _self_

hydra:
  run:
    dir: logs/run/${now:%Y-%m-%d}/${now:%H-%M-%S}${log.file_suffix}
  sweep:
    dir: logs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}${log.file_suffix}
  output_subdir: config

log:
  file_suffix: ""
  record_level: info # one of [debug, info, warning, error, critical]

root_dir: ${hydra:runtime.cwd}
log_dir: ${hydra:runtime.output_dir}
image_dir: ${log_dir}/image
notes_path: ${log_dir}/notes.txt
random_seed: 0
